#!/bin/sh

resolv_file=$(cat /etc/dnsmasq.conf |grep 'resolv-file=' |tail -n1 |cut -d'=' -f2)
default_dns_ip=$(cat $resolv_file |head -n1 |cut -d' ' -f2)

if [ -d /opt/etc/dnsmasq.d ]; then
    # 为默认的 /etc/dnsmasq.conf 新增配置.
    if ! fgrep -qs 'conf-dir=/opt/etc/dnsmasq.d/,*.conf' /etc/dnsmasq.conf; then
        cp /etc/dnsmasq.conf /etc/dnsmasq.conf.bak
        echo 'conf-dir=/opt/etc/dnsmasq.d/,*.conf' >> /etc/dnsmasq.conf
    fi

    domain_config=/opt/etc/dnsmasq.d/accelerated-domains.china.conf
    user_domain_name_whitelist=/opt/etc/user_domain_name_whitelist.txt

    if [ -f $user_domain_name_whitelist ]; then
        rm -f /opt/etc/dnsmasq.d/whitelist-domains.china.conf
        for i in $(cat $user_domain_name_whitelist); do
            echo "server=/${i}/${default_dns_ip}" >> /opt/etc/dnsmasq.d/whitelist-domains.china.conf
        done
        chmod +x /opt/etc/restart_dnsmasq && /opt/etc/restart_dnsmasq
    fi

    if [ -s ${domain_config}.bak ]; then
        sed "s#114\.114\.114\.114#${default_dns_ip}#" ${domain_config}.bak > $domain_config
    else
        /opt/etc/update_dns_whitelist
    fi

    chmod +x /opt/etc/restart_dnsmasq && /opt/etc/restart_dnsmasq
fi

if [ -e /opt/etc/init.d/S56chinadns ]; then
    sed -i "s#-s [0-9.]*,#-s ${default_dns_ip},#" /opt/etc/init.d/S56chinadns
    /opt/etc/init.d/S56chinadns restart
fi

if [ -e /opt/etc/dnscrypt-proxy.sh ]; then
    source /opt/etc/dnscrypt-proxy.sh
    [ "$tcp_only" == true ] && tcp_only_arg='-T'

    sed -i "s#^ARGS=.*#ARGS=\"${tcp_only_arg} -a 127.0.0.1:65053 -r ${resolver_address_with_port} -N ${provider_name} -k ${provider_key} -l /tmp/dnscrypt-proxy.log\"#" /opt/etc/init.d/S09dnscrypt-proxy
    /opt/etc/init.d/S09dnscrypt-proxy restart
fi

chmod +x /opt/etc/iptables.sh && /opt/etc/iptables.sh
