#!/bin/sh

if [ -d /opt/etc/dnsmasq.d ]; then
    # 为默认的 /etc/dnsmasq.conf 新增配置.
    if ! fgrep -qs 'conf-dir=/opt/etc/dnsmasq.d/,*.conf' /etc/dnsmasq.conf; then
        cp /etc/dnsmasq.conf /etc/dnsmasq.conf.bak
        echo 'conf-dir=/opt/etc/dnsmasq.d/,*.conf' >> /etc/dnsmasq.conf
    fi

    /opt/etc/restart_dnsmasq
fi

if [ -e /opt/etc/init.d/S56chinadns ]; then
    sed -i "s#-s [0-9.]*,#-s ${default_dns_ip},#" /opt/etc/init.d/S56chinadns
    /opt/etc/init.d/S56chinadns restart
fi

if [ -e /opt/etc/dnscrypt-proxy.sh ]; then
    source /opt/etc/dnscrypt-proxy.sh
    set -u

    if cat /opt/etc/dnsmasq.d/foreign_domains.conf  |grep '65053'; then
        dnscrypt_udp_only="-T"
    else
        dnscrypt_udp_only=""
    fi

    sed -i "s#^ARGS=.*#ARGS=\"$dnscrypt_udp_only -a 127.0.0.1:65053 -r ${resolver_address_with_port} -N ${provider_name} -k ${provider_key} -l /tmp/dnscrypt-proxy.log\"#" /opt/etc/init.d/S09dnscrypt-proxy
    /opt/etc/init.d/S09dnscrypt-proxy restart
fi
