#!/bin/sh

if [ -d /opt/etc/dnsmasq.d ]; then
    # 为默认的 /etc/dnsmasq.conf 新增配置.
    if ! fgrep -qs 'conf-dir=/opt/etc/dnsmasq.d/,*.conf' /etc/dnsmasq.conf; then
        cp /etc/dnsmasq.conf /etc/dnsmasq.conf.bak
        echo 'conf-dir=/opt/etc/dnsmasq.d/,*.conf' >> /etc/dnsmasq.conf
    fi
    dnsmasq --test && kill $(cat /var/run/dnsmasq.pid) && dnsmasq --log-async
fi
