#!/bin/sh

resolv_file=$(cat /etc/dnsmasq.conf |grep 'resolv-file=' |tail -n1 |cut -d'=' -f2)
default_dns_ip=$(cat $resolv_file |head -n1 |cut -d' ' -f2)

if [ -d /opt/etc/dnsmasq.d ]; then
    # 为默认的 /etc/dnsmasq.conf 新增配置.
    if ! fgrep -qs 'conf-dir=/opt/etc/dnsmasq.d/,*.conf' /etc/dnsmasq.conf; then
        cp /etc/dnsmasq.conf /etc/dnsmasq.conf.bak
        echo 'conf-dir=/opt/etc/dnsmasq.d/,*.conf' >> /etc/dnsmasq.conf
    fi
    cat /opt/etc/dnsmasq.d/accelerated-domains.china.conf.bak |sed "s#114\.114\.114\.114#${default_dns_ip}#" > /opt/etc/dnsmasq.d/accelerated-domains.china.conf
    dnsmasq --test && kill $(cat /var/run/dnsmasq.pid) && dnsmasq --log-async
fi

if [ -e /opt/etc/init.d/S56chinadns ]; then
    sed -i "s#-s [0-9.]*,#-s ${default_dns_ip},#" /opt/etc/init.d/S56chinadns
    /opt/etc/init.d/S56chinadns restart
fi

if [ -e /opt/etc/dnscrypt-proxy.sh ]; then
    source /opt/etc/dnscrypt-proxy.sh
    set -u

    if cat /opt/etc/dnsmasq.d/foreign_domains.conf  |grep '65053'; then
        dnscrypt_udp_only="-T"
    else
        dnscrypt_udp_only=""
    fi

    sed -i "s#^ARGS=.*#ARGS=\"$dnscrypt_udp_only -a 127.0.0.1:65053 -r ${resolver_address_with_port} -N ${provider_name} -k ${provider_key}\"#" /opt/etc/init.d/S09dnscrypt-proxy
    /opt/etc/init.d/S09dnscrypt-proxy restart
fi
