#!/bin/sh

set -e

wget -O - 'http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest' |
    awk -F\| '/CN\|ipv4/ { printf("%s/%d\n", $4, 32-log($5)/log(2)) }' > /opt/etc/chinadns_chnroute.new

if [ -s /opt/etc/chinadns_chnroute.new ]; then
    mv /opt/etc/chinadns_chnroute.new /opt/etc/chinadns_chnroute.txt
fi

/opt/etc/init.d/S56chinadns restart
