#!/bin/sh

set -e

echo 'Update domain name whitelist ...'

domain_config=/opt/etc/dnsmasq.d/accelerated-domains.china.conf

wget --no-check-certificate https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf -O ${domain_config}.bak

/opt/etc/patch_dnsmasq

# cat /opt/etc/dnsmasq.d/accelerated-domains.china.conf.bak |
#     sed 's#server=\(.*\)114.114.114.114#ipset=\1FREEWEB#' |
#     sed "s|^\(server.*\)/[^/]*$|\1/#|" > /opt/etc/dnsmasq.d/accelerated-domains-ipset.china.conf
