#!/bin/sh

resolv_file=$(cat /etc/dnsmasq.conf |grep 'resolv-file=' |tail -n1 |cut -d'=' -f2)

if [ "$resolv_file" ]; then
    default_dns_ip=$(cat $resolv_file |head -n1 |cut -d' ' -f2)
else
    default_dns_ip='114.114.114.114'
fi

dnsmasq_dir=/opt/etc/dnsmasq.d

if [ -d "$dnsmasq_dir" ]; then
    # 为默认的 /etc/dnsmasq.conf 新增配置.
    if ! grep -qs "^conf-dir=$dnsmasq_dir/,\*\.conf$" /etc/dnsmasq.conf; then
        echo "conf-dir=$dnsmasq_dir/,*.conf" >> /etc/dnsmasq.conf
    fi

    accelerated=accelerated-domains.china.conf
    google=google.china.conf
    apple=apple.china.conf

    user_domain_name_whitelist=/opt/etc/user_domain_name_whitelist.txt
    user_domain_name_blocklist=/opt/etc/user_domain_name_blocklist.txt

    if [ -f $user_domain_name_whitelist ]; then
        rm -f $dnsmasq_dir/whitelist-domains.china.conf
        for i in $(cat $user_domain_name_whitelist); do
            echo "server=/${i}/${default_dns_ip}" >> $dnsmasq_dir/whitelist-domains.china.conf
        done
    fi

    if [ -f $user_domain_name_blocklist ]; then
        rm -f $dnsmasq_dir/blacklist-domains.china.conf
        for i in $(cat $user_domain_name_blacklist); do
            echo "address=/${i}/127.0.0.1" >> $dnsmasq_dir/blocklist-domains.china.conf
        done
    fi

    if ! [ -s $dnsmasq_dir/$accelerated.bak ]; then
        /opt/etc/update_dns_whitelist
    fi

    if ! [ -s /opt/etc/chinadns_chnroute.txt ]; then
        /opt/etc/update_ip_whitelist
    fi

    sed "s#114\.114\.114\.114#${default_dns_ip}#" $dnsmasq_dir/$accelerated.bak > $dnsmasq_dir/$accelerated
    sed "s#114\.114\.114\.114#${default_dns_ip}#" $dnsmasq_dir/$google.bak > $dnsmasq_dir/$google
    sed "s#114\.114\.114\.114#${default_dns_ip}#" $dnsmasq_dir/$apple.bak > $dnsmasq_dir/$apple

    chmod +x /opt/etc/restart_dnsmasq && /opt/etc/restart_dnsmasq
fi

if [ -e /opt/etc/init.d/S56chinadns ]; then
    sed -i "s#-s [0-9.]*,#-s ${default_dns_ip},#" /opt/etc/init.d/S56chinadns
    /opt/etc/init.d/S56chinadns restart
fi

if [ -e /opt/etc/dnscrypt-proxy.sh ]; then
    source /opt/etc/dnscrypt-proxy.sh

    [ "$tcp_only" == true ] && tcp_only_arg='-T'

    sed -i "s#^ARGS=.*#ARGS=\"${tcp_only_arg} -a 127.0.0.1:65053 -r ${resolver_address_with_port} -N ${provider_name} -k ${provider_key} -l /tmp/dnscrypt-proxy.log\"#" /opt/etc/init.d/S09dnscrypt-proxy
    /opt/etc/init.d/S09dnscrypt-proxy restart
fi

/opt/etc/iptables.sh
