#!/bin/sh

set -e

echo 'Update DNS whitelist ...'

/opt/etc/toggle_proxy.sh disable

domain_config=/opt/etc/dnsmasq.d/accelerated-domains.china.conf

wget --no-check-certificate https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf -O ${domain_config}.bak

echo "server=/entware.net/114.114.114.114" >> ${domain_config}.bak
echo "server=/githubusercontent.com/114.114.114.114" >> ${domain_config}.bak

# 为默认的 /etc/dnsmasq.conf 新增配置.
if ! grep -qs '^conf-dir=/opt/etc/dnsmasq.d/,\*\.conf$' /etc/dnsmasq.conf; then
    echo 'conf-dir=/opt/etc/dnsmasq.d/,*.conf' >> /etc/dnsmasq.conf
fi

/opt/etc/toggle_proxy.sh

echo 'Update DNS whitelist done.'

# cat /opt/etc/dnsmasq.d/accelerated-domains.china.conf.bak |
#     sed 's#server=\(.*\)114.114.114.114#ipset=\1FREEWEB#' |
#     sed "s|^\(server.*\)/[^/]*$|\1/#|" > /opt/etc/dnsmasq.d/accelerated-domains-ipset.china.conf
