#!/bin/sh

set -e

echo 'Update DNS whitelist ...'

/opt/etc/toggle_proxy.sh disable

accelerated=accelerated-domains.china.conf
google=google.china.conf
apple=apple.china.conf

download_url=https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master
dnsmasq_dir=/opt/etc/dnsmasq.d

wget --no-check-certificate $download_url/$accelerated -O $dnsmasq_dir/$accelerated.bak
wget --no-check-certificate $download_url/$google -O $dnsmasq_dir/$google.bak
wget --no-check-certificate $download_url/$apple -O $dnsmasq_dir/$apple.bak

/opt/etc/toggle_proxy.sh

echo 'Update DNS whitelist done.'
