#!/bin/sh

self="$(curl https://raw.githubusercontent.com/zw963/deployment_bash/v0.5.2/deploy_start.sh)" && eval "$self"

# if [ -z "$*" ]; then
#     dockerinit /docker

#     exit 0
# fi

export target=$1

deploy_start

docker ps &>/dev/null || dockerinit /docker

set +e
docker rm -f dnscrypt-server
set -e

docker run -d \
       --name=dnscrypt-server \
       -p 22337:443/udp \
       -p 22337:443/tcp \
       jedisct1/dnscrypt-server \
       init \
       -N example_2.online \
       -E ${targetip}:22337

sleep 2
docker start dnscrypt-server
docker update --restart=always dnscrypt-server
sleep 2
docker logs dnscrypt-server

# Add Stamp for dnscrypt-proxy 2.x in above logs to router /opt/etc/dnscrypt-wrapper.toml.
