#!/bin/bash


target='route/opt/etc/dnsmasq.d/'

mkdir -p $target

# -O 参数，确保目标文件总是被覆盖。
if ! which wget &>/dev/null; then
    echo 'Please install wget! e.g. sudo apt-get install wget'
    exit 1
fi

# wget -q -O $target/bogus-nxdomain.china.conf https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/bogus-nxdomain.china.conf
# wget -q -O $target/google.china.conf https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/google.china.conf

wget -q -O - https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf |
    sed 's#server=\(.*\)114.114.114.114#ipset=\1FREEWEB#' |
    sed "s|^\(server.*\)/[^/]*$|\1/#|" > $target/accelerated-domains-ipset.china.conf
