#!/bin/bash

[ -e /opt/etc/iptables_disable.sh ] && sh /opt/etc/iptables_disable.sh

date=$(date '+%Y-%m-%d_%H-%M-%S')
mv /tmp/mnt/sda1/entware /tmp/mnt/sda1/entware_bak_$date
cp -a /tmp/mnt/sda1/entware.bak /tmp/mnt/sda1/entware

if fgrep -qs 'conf-dir=/opt/etc/dnsmasq.d/,*.conf' /etc/dnsmasq.conf; then
    sed -i 's#conf-dir=/opt/etc/dnsmasq.d/,\*\.conf$##g' /etc/dnsmasq.conf
fi
dnsmasq --test && kill $(cat /var/run/dnsmasq.pid) && dnsmasq --log-async

rm -f /opt/var/lock/opkg.lock

exit
