#!/bin/bash

# run following command to reset router
# $: ssh admin@router.asus.com <<< "$(cat init_router)"

[ -e /opt/etc/toggle_proxy.sh ] && sh /opt/etc/toggle_proxy.sh disable

date=$(date '+%Y-%m-%d_%H-%M-%S')
mv /tmp/mnt/sda1/entware /tmp/mnt/sda1/entware_bak_$date
cp -a /tmp/mnt/sda1/entware.bak /tmp/mnt/sda1/entware

rm -f /opt/var/lock/opkg.lock

cat <<'HEREDOC' > /jffs/scripts/services-start
#!/bin/sh

RC='/opt/etc/init.d/rc.unslung'

i=30
until [ -x "$RC" ] ; do
  i=$(($i-1))
  if [ "$i" -lt 1 ] ; then
    logger "Could not start Entware"
    exit
  fi
  sleep 1
done
$RC start
HEREDOC
exit

echo '' > /jffs/scripts/wan-start
