#!/bin/sh

source ./functions/deploy_start.sh

export target=$1

if [ ! -e ./route/opt/etc/shadowsocks.json ];then
    echo '请首先定义 route/opt/etc/shadowsocks.json'
    exit
fi

# 在本地生成 dnsmasq 需要的国内域名白名单列表。
./generate_dns

# 部署开始，这里首先会将 route 目录下的所有文件同步到路由器。
deploy_start

# ----------------------------------------------------
#
# 下面的脚本会在远程路由器之上执行, 请根据所需，酌情修改。
#
# ---------------------------------------------------

# 初始化 entware. 建议手动执行。
# ssh entware-setup.sh; opkg update && opkg upgrade

#  安装一些有用的工具，编辑器, 离线下载等等.
opkg install grep nano findutils-locate wget aria2 sed
# ssh 登陆路由器时，添加了一些别名，请自行查看。
add_service post-mount 'cp /opt/etc/profile /root/.profile'
# 使用 Asus Merlin 提供的 Custom config files 能力，将这条配置加入 dnsmasq.conf 中.
echo 'conf-dir=/opt/etc/dnsmasq.d/,*.conf' > /jffs/configs/dnsmasq.conf.add
# 确保 iptables.sh 可执行, 并加入计划任务，延迟执行。
chmod +x /opt/etc/iptables.sh
add_service services-start 'cru a iptables-nat "*/1 * * * *" "/opt/etc/iptables.sh"'
# 安装 shadowsocks-libev + chinadns + iptables + ipset4
opkg install shadowsocks-libev chinadns iptables ipset4

# ----------------------------------------------------
#
# 下面执行一些脚本检查与替换。
#
# ---------------------------------------------------

# 确保 shadowsocks.json 中的 local_address 替换为路由器 ip 地址。
replace_regex '"local_address".*' '"local_address":'"\"$targetip\"," /opt/etc/shadowsocks.json
# 取得 shadowsocks.json 中的服务器 ip 地址以及 ss-redir 端口, 并自动替换 iptables.sh 中对应的值。
ss_server_ip=$(cat /opt/etc/shadowsocks.json |grep 'server"' |cut -d':' -f2|cut -d'"' -f2)
ss_local_port=$(cat /opt/etc/shadowsocks.json |grep 'local_port"' |grep -o '[0-9]*')
replace_string 'SS_SERVER_IP' $ss_server_ip /opt/etc/iptables.sh
replace_string 'SS_LOCAL_PORT' $ss_local_port /opt/etc/iptables.sh
# 修改 chinadns 的 port 为 5356, 并修改 dnsmasq.d 中对应内容。
replace_string 5353 5356 /opt/etc/init.d/S56chinadns
replace_string CHINADNS_PORT 5356 /opt/etc/dnsmasq.d/foreign_domains.conf
# 默认 shadowsocks 启动脚本使用 ss-redir 而不是 ss-local.
replace_string ss-local ss-redir /opt/etc/init.d/S22shadowsocks
# 定时检测所有服务是否正常运行。
add_service services-start 'cru a run-services "*/1 * * * *" "/jffs/scripts/services-start"'
# 重启 dnsmasq 服务器。
dnsmasq --test && kill $(cat /var/run/dnsmasq.pid) && dnsmasq --log-async
# 重启, 如果遇到问题，拔下 U 盘，再次重启后，再插上 U 盘，修复错误。
# reboot
