#!/bin/bash

self="$(curl -sS https://raw.githubusercontent.com/zw963/deployment_bash/v0.3.7/deploy_start.sh)" && eval "$self"

# self="$(cat ~/Project/deployment_bash/deploy_start.sh)" && eval "$self"

export target=$1

if [ ! -e ./route/opt/etc/shadowsocks.json ];then
    echo '请首先定义 route/opt/etc/shadowsocks.json'
    exit
fi

copy route/opt/etc/dnscrypt-proxy.sh /opt/etc
copy route/opt/etc/dnsmasq.d/foreign_domains.conf /opt/etc/dnsmasq.d/foreign_domains.conf
copy route/opt/etc/iptables.sh /opt/etc
copy route/opt/etc/toggle_proxy.sh /opt/etc
copy route/opt/etc/patch_route /opt/etc
copy route/opt/etc/restart_dnsmasq /opt/etc
copy route/opt/etc/shadowsocks.json /opt/etc
copy route/opt/etc/localips /opt/etc
copy route/opt/etc/update_ip_whitelist /opt/etc
copy route/opt/etc/update_dns_whitelist /opt/etc

[ -e route/opt/etc/user_ip_whitelist.txt ] && copy route/opt/etc/user_ip_whitelist.txt /opt/etc
[ -e route/opt/etc/user_domain_name_whitelist.txt ] && copy route/opt/etc/user_domain_name_whitelist.txt /opt/etc

deploy_start

/opt/etc/toggle_proxy.sh disable

# ----------------------------------------------------
#
# 下面的脚本会在远程路由器之上执行, 请根据所需，酌情修改。
#
# ---------------------------------------------------

# 如果第一次运行本脚本, 请务必初始化 entware 包管理系统.
# ssh 登陆路由器, 执行 entware-setup.sh, 选择 1'

if ! opkg update; then
    echo "Run \`opkg update' failed."
    echo "Run \`entware-setup.sh' to initalize entware-ng!"
    exit
else
    opkg upgrade
fi

# 如果不存在 ipset (例如 AC66U), 首先安装 ipset4
which ipset &>/dev/null || opkg install ipset4

# 添加 AC87U 的 ipset protocal version 6 的 iptables/ipset 支持.
ipset_protocal_version=$(ipset -v |grep -o 'version.*[0-9]' |head -n1 |cut -d' ' -f2)

set -e

opkg install libc libssp libev libmbedtls libpcre libpthread libsodium haveged zlib libopenssl

if opkg find shadowsocks-libev |grep -qs -e '.*'; then
    opkg install shadowsocks-libev
elif opkg find shadowsocks-libev-ss-redir |grep -qs -e '.*'; then
    opkg install shadowsocks-libev-ss-redir
fi

opkg install dnscrypt-proxy
# opkg install bind-dig

if [ "$ipset_protocal_version" == 6 ]; then
    # AC87U 无需安装新版的 iptables/ipset
    echo 'skip install iptables'
else
    # AC66U, 需要额外安装新版的 iptables
    opkg install iptables
fi

# ----------------------------------------------------
#
# 下面执行一些脚本检查与替换。
#
# ---------------------------------------------------

# 确保 shadowsocks.json 中的 local_address 替换为路由器 ip 地址。
replace_regex '"local_address".*' '"local_address":'"\"$targetip\"," /opt/etc/shadowsocks.json

# 将 dnscrypt 作为 dnsmasq 的上游 DNS 服务器
replace_regex 'server=/#/.*' 'server=/#/127.0.0.1#65053' /opt/etc/dnsmasq.d/foreign_domains.conf
#
# 默认 shadowsocks 启动脚本使用 ss-redir 而不是 ss-local, 端口 1080.
replace_string ss-local ss-redir /opt/etc/init.d/S22shadowsocks

# ----------------------------------------------------
#
# 启动所需的脚本
#
# ---------------------------------------------------

# 每隔 1 分钟检测下所有的服务是否运行.
add_service wan-start 'cru a run-services "*/1 * * * *" "/jffs/scripts/services-start"'
# 每隔 3 分钟检测下 iptables 是否失效.
add_service wan-start 'cru a run-iptables "*/3 * * * *" "/opt/etc/iptables.sh"'

# 星期一的 3:25 分升级 IP 白名单.
chmod +x /opt/etc/update_ip_whitelist && /opt/etc/update_ip_whitelist
add_service wan-start 'cru a update_ip_whitelist "25 3 * * 2" "/opt/etc/update_ip_whitelist"'

# 星期一的 3:15 分升级域名白名单.
chmod +x /opt/etc/update_dns_whitelist && /opt/etc/update_dns_whitelist
add_service wan-start 'cru a update_dns_whitelist "15 3 * * 2" "/opt/etc/update_dns_whitelist"'

set +e
/jffs/scripts/services-stop
set -e
/jffs/scripts/services-start

chmod +x /opt/etc/patch_route && /opt/etc/patch_route
# 在所有服务启动之后, 运行 /opt/etc/patch_route, 为 dnsmasq 追加配置, 并重启 dnsmasq 服务.
add_service services-start '
if [ ! -f /tmp/patch_route_is_run ];then
    /opt/etc/patch_route && touch /tmp/patch_route_is_run
fi
'

echo '貌似部署成功了!'
echo
echo '如果无法翻墙, 按照下列步骤查错:'
echo '1. 断掉已连接的 WiFi, 并重新连接, 看看是否可以翻墙.'
echo '2. 保持 U 盘, 重启路由器, 并等待片刻, 看看是否可以翻墙.'
echo '3. 检查 /opt/etc 下配置文件, 并运行 /jffs/scripts/services-stop; /jffs/scripts/services-start 重启所有服务'
echo
echo  '如果需要重新部署.'
echo '1. 进入管理界面, 选择格式化 jffs, 并重启'
echo '2. 使用 entware-setup.sh 重新初始化包管理系统'
echo '3. 使用本脚本再次部署'
echo
echo  '如果无法连接路由器.'
echo '1. 拔下 U 盘, 重启, 尝试重新连接路由器'
echo '2. 进入管理界面, 选择格式化 jffs, 并重启'
# reboot
